# taken from numart code
language: elixir
elixir:
  - 1.5.2
otp_release:
  - 20.1
before_script:
  - psql -U postgres -c "CREATE USER microblog WITH CREATEUSER PASSWORD 'ahJ8wuagi9';"
  - psql -U postgres -c "CREATE DATABASE microblog_test;"
